{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.material",
    "module": "material",
    "version": "1.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.14.0.aar",
          "url": "material-1.14.0.aar",
          "size": 2747279,
          "sha512": "29de570a48301bf8e1b58e37a743f8f9a1acb870dadda27e264f05b989690eaf8dcde5b026e9f431aa8e4e9349d128fa45c4a7b8bbadc1f78c905c040210cf60",
          "sha256": "7e2ce2ea22eb854c07e24c21f59d6ed8861269a771f616c461a30854672f55ab",
          "sha1": "e9dd938a9b07d3d5edbaed79f793da9e638503eb",
          "md5": "3a0864a34832b04ad4fa846d7c6970c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.14.0.aar",
          "url": "material-1.14.0.aar",
          "size": 2747279,
          "sha512": "29de570a48301bf8e1b58e37a743f8f9a1acb870dadda27e264f05b989690eaf8dcde5b026e9f431aa8e4e9349d128fa45c4a7b8bbadc1f78c905c040210cf60",
          "sha256": "7e2ce2ea22eb854c07e24c21f59d6ed8861269a771f616c461a30854672f55ab",
          "sha1": "e9dd938a9b07d3d5edbaed79f793da9e638503eb",
          "md5": "3a0864a34832b04ad4fa846d7c6970c3"
        }
      ]
    }
  ]
}
