{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.zhihulite",
    "module": "luajvm-android",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.zhihulite",
          "module": "luajvm-core-android",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-splashscreen",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "5.0.9"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.github.Baseflow",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "luajvm-android-1.0.0.aar",
          "url": "luajvm-android-1.0.0.aar",
          "size": 313827,
          "sha512": "7281a5f96fc283dfa85ae92f28c15c33cf9a50f106f531e98ee9c84550e713d47dd80b7b97ac5f664884273d44d007a6d455301ac526ec678b7e68b90b8f2258",
          "sha256": "95636a8a7c54f2a369d48c8f091e7fb093eee826a21b6390200e318171734d50",
          "sha1": "98469f338f87c110a839cad0d561f0e81988411a",
          "md5": "c6ce11c6725d44d8f62b4a14437f0f37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.linkedin.dexmaker",
          "module": "dexmaker",
          "version": {
            "requires": "2.28.6"
          }
        },
        {
          "group": "io.github.zhihulite",
          "module": "luajvm-core-android",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-splashscreen",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "5.0.9"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.github.Baseflow",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "luajvm-android-1.0.0.aar",
          "url": "luajvm-android-1.0.0.aar",
          "size": 313827,
          "sha512": "7281a5f96fc283dfa85ae92f28c15c33cf9a50f106f531e98ee9c84550e713d47dd80b7b97ac5f664884273d44d007a6d455301ac526ec678b7e68b90b8f2258",
          "sha256": "95636a8a7c54f2a369d48c8f091e7fb093eee826a21b6390200e318171734d50",
          "sha1": "98469f338f87c110a839cad0d561f0e81988411a",
          "md5": "c6ce11c6725d44d8f62b4a14437f0f37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "luajvm-android-1.0.0-sources.jar",
          "url": "luajvm-android-1.0.0-sources.jar",
          "size": 196205,
          "sha512": "96950cb6067a81dbc04f52a99e2f876619ed4295cf0e8c2f865feca62c58ef6ffe265f9f03cc9b4f5a1f25b0f1cbb2bbbb9d2e6eef0b500dfd673c837211af25",
          "sha256": "ced2b344534ded81791e20e238887302252dbc2237721a303eb5799b51e9c736",
          "sha1": "c18f614a410a215e488c071e89c7112cee7fea99",
          "md5": "1fd0976e92919d4ec85b4c17ae3edaf5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "luajvm-android-1.0.0-javadoc.jar",
          "url": "luajvm-android-1.0.0-javadoc.jar",
          "size": 1186107,
          "sha512": "feb0031a8fb367118dd9168594264a9b87d8e6e57c5e553b1f8d02276275d219b6b4315d859c257156a0fd125b724deb7e036c94c4e1523e0509ad837c8ebc28",
          "sha256": "098263daa94c2eb6139bc23975c265aae3f2657657b2762667769314ee4dc40e",
          "sha1": "e9af913dcbc47a126d501cf5977eefc2d77bb805",
          "md5": "a9b452805721b9aea7bb196dc955e52d"
        }
      ]
    }
  ]
}
